# Generated by Django 3.2.13 on 2022-05-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='roll_no',
        ),
    ]
