# Generated by Django 3.2.13 on 2022-05-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0002_auto_20220502_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='roll_no',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='subject_code',
            new_name='subject',
        ),
    ]
